name: Windows Build & Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v4

    - name: Configurar Python (para o Conan)
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Instalar e Configurar Conan
      run: |
        pip install conan
        conan profile detect --force

    - name: Instalar Dependências
      run: |
        conan install --output-folder=build --build=missing -s build_type=Release -s compiler.cppstd=17

    - name: Configurar CMake
      run: cmake --preset conan-default

    - name: Compilar Projeto (Release)
      run: cmake --build --preset conan-release

    - name: Rodar Testes

      run: ctest --preset conan-release --output-on-failure

    - name: Preparar Artefatos (Install)

      run: cmake --install build --prefix package --config Release

    - name: Criar Release no GitHub
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          package/bin/Bry_API.exe
          package/bin/Bry_CLI.exe
          package/bin/*.dll
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}